### ISSUE TITLE
Camera & WiFi Not Working

### ISSUE THREAD

**Issue by dylangerdaly** [sonyxperiadev/device-sony-kirin#1]
Hello,

The Camera and WiFi currently do not work on the Xperia 10 (AOSP System, Boot and Vendor Images with SW_binaries_for_Xperia_Android_9.0_2.3.2_v7_ganges.zip)

Camera Log: https://pastebin.com/erqxejDx
WiFi Log: https://pastebin.com/Jn76L8ac

**Comment by jerpelea** [comment]
We are working on the functionality and we will enable it as soon as possible

**Comment by jerpelea** [comment]
the wifi was fixed 
please sync and build

**Comment by dylangerdaly** [comment]
Thank you, can confirm WiFi is fixed.

However the Camera is still not working, should I create another ticket?

**Comment by jerpelea** [comment]
camera is not supposed to work yet

**Comment by lucasponez** [comment]
Do you have a commit for device tree to fix wifi as related in log above?
